### PR TITLE
Attach tags asynchronously

### LINKED ISSUE #322: Tag set upfront on the receive BTC invoice is not displayed on incoming transaction
Steps to reproduce:

1. On main screen tap `Receive` and edit invoice.
2. Add tag to invoice (e.g. `rtag1`).
3. Send funds to the invoice address.
4. Funds received and transaction is listed on activity details.
5. Go to incoming transaction details and see that there is no tag `rtag1` assigned to transaction.
**Note:** in Bitkit RN the transaction is tagged in such scenario.
6. Note you can tag this transaction now and `rtag1` is visible in previously used tags list, but in Bitkit RN such tx was already tagged.

See video:

https://github.com/user-attachments/assets/84db8a58-056d-4c52-acd3-3583707bbe54

### PR DESCRIPTION
**Pull request by jvsena42**
Closes #322 

### Description
Currently, the app only tries to attach pending tags when the event is received, so it may fail if the activity takes to long to be added. 
This implementation syncs the pending tags on every activity sync

- [x] Check pending tags every time the balance changes
- [x] Fix receive onChain flow
   - [x] Save the on-chain address and transaction direction in the tags MetaData
   - [x] Migrations
   - [x] on balance changes, check for pending on-chain receive tags

### Preview

https://github.com/user-attachments/assets/8f6bc4b3-9bfb-41f9-84bb-f9d2536f53e5

https://github.com/user-attachments/assets/90c173bf-8a0d-4498-bd22-cbb5b124619d

https://github.com/user-attachments/assets/fb3bc8c0-02df-4b26-ab7e-e61de11a7745

https://github.com/user-attachments/assets/f5b29ed7-8d04-4191-a6aa-db11a3b9eb83

### QA Notes
Tests
- [x] OnChain
    - [x] Add tags before sending -> send -> check if tags were attached in activity details
    - [x] Create an invoice -> add tags -> receive -> check if tags were attached in activity details

- [x] Lightning
    - [x] Add tags before sending -> send -> check if tags were attached in activity details
    - [x] Create an invoice -> add tags -> receive -> check if tags were attached in activity details

### CODE REVIEW

File: app/src/main/java/to/bitkit/repositories/ActivityRepo.kt [hunk 1]
```diff
@@ -53,8 +60,11 @@ class ActivityRepo @Inject constructor(
             return@withContext lightningRepo.getPayments()
                 .onSuccess { payments ->
                     Logger.debug("Got payments with success, syncing activities", context = TAG)
-                    syncLdkNodePayments(payments = payments)
+                    syncLdkNodePayments(payments = payments).onFailure { e ->
+                        return@withContext Result.failure(e)
+                    }
                     updateActivitiesMetadata()
+                    syncTagsMetaData()
```
Comment (ovitrif) [inline app/src/main/java/to/bitkit/repositories/ActivityRepo.kt:67]: nit: `MetaData` caps NOK, should be `Metadata`

File: app/src/main/java/to/bitkit/repositories/ActivityRepo.kt [hunk 2]
```diff
@@ -330,6 +322,79 @@ class ActivityRepo @Inject constructor(
         }
     }
 
+    private suspend fun syncTagsMetaData(
+    ) = withContext(context = bgDispatcher) {
+        runCatching {
+            if (db.tagMetadataDao().getAll().isEmpty()) return@withContext
+            val lastActivities = getActivities(limit = 10u).getOrNull() ?: return@withContext
+            Logger.debug("syncTagsMetaData called")
+            lastActivities.forEach { activity ->
```
Comment (ovitrif) [inline app/src/main/java/to/bitkit/repositories/ActivityRepo.kt:331]: Computation inside `forEach` block should be parallelized later, when optimising for performance.

File: app/src/main/java/to/bitkit/repositories/ActivityRepo.kt [hunk 3]
```diff
@@ -504,6 +569,37 @@ class ActivityRepo @Inject constructor(
...
+        id: String,
+        paymentHash: String? = null,
+        txId: String? = null,
+        address: String,
+        isReceive: Boolean,
+        tags: List<String>,
+    ): Result<Unit> = withContext(bgDispatcher) {
+        return@withContext runCatching {
+
+            if (tags.isEmpty()) throw InvalidParameterException("tags must not be empty")
```
Comment (ovitrif) [inline app/src/main/java/to/bitkit/repositories/ActivityRepo.kt:582]: `InvalidParameterException` is not intended for such uses, apparently.
Should be replaced by `IllegalArgumentException`

**Review by ovitrif — APPROVED** [review]
LGTM 🎉 

Added a few remarks but nothing blocking.

File: app/src/main/java/to/bitkit/repositories/ActivityRepo.kt (hunk 3 above)
Comment (jvsena42) [reply app/src/main/java/to/bitkit/repositories/ActivityRepo.kt:582]: I intended to implement `InvalidParameterException`. It was probably the autocomplemente, thanks!
