### PR TITLE
CJIT receive Sheets

### LINKED ISSUE #359: Unnecessary/misleading notification on connecting to external LND channel
Observed while testing on the backend from e2e tests (see: [bitkit-e2e-tests/docker](https://github.com/synonymdev/bitkit-e2e-tests/tree/main/docker)).

**Steps to reproduce:** (e2e test: `@send_2 - Can receive funds and send to different invoices`)
1. Create and fund wallet.
2. Set up and LND channel and connect to it from bitkit (Settings > Advanced > Lightning Connections > Add connection > Advanced > Manual Setup)
3. Fill node id, host: `0.0.0.0`, port: `9735`
4. Continue.
5. Open the channel.

The notification pops up:

Image

See video:

https://github.com/user-attachments/assets/08035f13-6b15-4c62-835c-778b30f33a04

### PR DESCRIPTION
**Pull request by jvsena42**
Closes #359 
Closes https://github.com/synonymdev/bitkit-android/pull/378#discussion_r2352779718
Closes https://github.com/synonymdev/bitkit-android/pull/378#discussion_r2352860607

### Description
This PR fixes the CJIT and channel notifications

- Display transaction received sheet in channel event only for CJIT
- Display correct sendable amount in CJIT sheet
- Display LN toast for channel notification

### Preview

[cjit.webm](https://github.com/user-attachments/assets/98bc2f02-24ab-46c1-93a7-34abf0b7f62d)

[transfer.webm](https://github.com/user-attachments/assets/01ac1fab-8824-49f1-af53-02fb900be2ba)

[external-node.webm](https://github.com/user-attachments/assets/b6683075-f941-4921-b50f-fe8a6ef75de7)

### QA Notes
Tested:

- [x] Receive CJIT > should display sheet with correct amount
- [x] Move balance from savings to spending > Should display channel toast
- [x] Connect to external node > Should display channel toast

### CODE REVIEW

**Comment by ovitrif** [comment]
Can you please also remove this toast for the time being, since this PR touches notifications related to channels?

Android Studio 2025-09-17 000392

File: app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt [hunk 1]
```diff
@@ -1499,12 +1493,18 @@ class AppViewModel @Inject constructor(
         setSendEffect(SendEffect.PaymentSuccess(details))
     }
 
+    private fun ChannelDetails.getAmountSend(): Long {
+        return ((this.outboundCapacityMsat / MILLISATS + (this.unspendablePunishmentReserve ?: 0UL))).toLong()
+    }
+
```
Comment (ovitrif) [inline app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt:1499]: Could use the existing extension instead, to avoid re-declaring the same thing : `ChannelDetails.amountOnClose`:

https://github.com/synonymdev/bitkit-android/blob/f2723323e557adb367bcfcb3900943bb92b934dc/app/src/main/java/to/bitkit/ext/ChannelDetails.kt#L10-L16

Name might not be perfect but close enough 👍🏻

**Review by ovitrif — CHANGES_REQUESTED** [review]
Tested all 3 cases with success 🟢 ,

requested a change to avoid code duplication

File: app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt (hunk 1 above)
Comment (jvsena42) [reply app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt]: Thanks!

File: app/src/main/java/to/bitkit/fcm/WakeNodeWorker.kt [hunk 2]
```diff
@@ -140,15 +141,15 @@ class WakeNodeWorker @AssistedInject constructor(
...
+                        val sats = channel.amountOnClose
                         self.bestAttemptContent?.title = "Received ⚡ $sats sats"
                         // Save for UI to pick up
                         NewTransactionSheetDetails.save(
                             appContext,
                             NewTransactionSheetDetails(
                                 type = NewTransactionSheetType.LIGHTNING,
                                 direction = NewTransactionSheetDirection.RECEIVED,
-                                sats = sats.toLong(),
+                                sats = channel.amountOnClose.toLong(),
```
Comment (ovitrif) [inline app/src/main/java/to/bitkit/fcm/WakeNodeWorker.kt:152]: was expecting to see `sats.toLong()` here :)

**Review by ovitrif — APPROVED** [review]
