### PR TITLE
fix: Fee above 10 USD sanity check and don't skip checks

### LINKED ISSUE #325: Over $10 fee warning pop-up when fee is below, on sending transaction
Observed while testing on the backend from e2e tests (see: [bitkit-e2e-tests/docker](https://github.com/synonymdev/bitkit-e2e-tests/tree/main/docker)).

Steps to reproduce:

1. Have some funds on the wallet.
2. Send ₿ `10 000` and swipe to confirm.
3. Notice the warning pop-up informing that fee is over $10.
4. Confirm.
5. Transaction sent. Notice that fee is just ₿ `143`, so much below $10.
6. Note that the whole sum ₿ `10 000`  is indeed over $10, but not the fee itself.
7. Note that when one sends ₿ `5 000` so the whole sum below $10, the warning is not presented.

See the video:

https://github.com/user-attachments/assets/146f19b0-a5fd-468b-a382-cca580847213

### LINKED ISSUE #328: Sending tx: single warning dialog when two expected
Observed while testing on the backend from e2e tests (see: [bitkit-e2e-tests/docker](https://github.com/synonymdev/bitkit-e2e-tests/tree/main/docker)).

**Steps to reproduce:**

1. Have ₿ `100 000 000` on the wallet.
2. Send ₿ `51 000 000` and swipe to confirm, i.e. over 50% of funds.
3. Notice the sending over 50% of balance warning pop-up appearing.
4. Cancel the tx.
5. Enable warning for sending over 100$. (Settings > Security and Privacy > Warn when sending over $100)
6. Go back and send again ₿ `51 000 000`. Swipe to confirm.
7. Notice the sending over 100$ warning pop-up appearing.
8. Confirm pop-up.

**Actual:**

Transaction is sent after confirming the "$100 warning".

**Expected:**

Both warning should be presented before sending the transaction.
Note that in Bitkit RN the order is as follows:
 - "50% warning"
 - "$100 warning"

See video:

https://github.com/user-attachments/assets/f1eb5ef9-e658-4e0a-8bbd-2232dfa35ee7

### PR DESCRIPTION
**Pull request by jvsena42**
Closes #325, Closes #328

### Description
This PR fixes the fee above 10 USD sanity check. The method was using the full sending amount instead of just the fee value.
Also check all the sanity checks instead of skipping the others after confirming the first one

### Preview

https://github.com/user-attachments/assets/96cd3d36-efb1-41f0-9553-c6af05f05120

https://github.com/user-attachments/assets/e54ca921-e766-48b7-b129-a17d0e1b7e60

### QA Notes

Steps to reproduce:

1. Have ₿ 100 000 000 in the wallet.
2. Send ₿ 51 000 000 and swipe to confirm, i.e., over 50% of funds.
3. Notice the sending over 50% of balance warning pop-up appearing.
4. Cancel the tx.
5. Enable the warning for sending over 100$. (Settings > Security and Privacy > Warn when sending over $100)
6. Go back and send again ₿ 51 000 000. Swipe to confirm.
7. Notice the sending over 100$ warning pop-up appearing.
8. Confirm pop-up.
9. Try to send with a fee of above 10 USD
10. Notice the pop-up appearing
11. Confirm pop-up
12. Try to send with a fee of above half the sending amount
13. Notice the pop-up
14. Confirm pop-up
15. No other pop-up should be displayed

### CODE REVIEW

File: app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt [hunk 1]
```diff
@@ -1364,20 +1377,21 @@ class AppViewModel @Inject constructor(
         }
     }
 
-    private fun onConfirmAmountWarning() {
+    private fun onConfirmAmountWarning(warning: SanityWarning) {
         viewModelScope.launch {
             _sendUiState.update {
                 it.copy(
-                    showAmountWarningDialog = null,
-                    shouldConfirmPay = true,
```
Comment (jvsena42) [inline app/src/main/java/to/bitkit/viewmodels/AppViewModel.kt:1372]: Setting `shouldConfirmPay` as true instead of calling `onSwipeToPay` again was causing #328
