### PR TITLE
fix: unify timed sheet behavior for master

### LINKED ISSUE #497: Unify timesheets behavior on Android to match iOS
Some context and discussion here: https://github.com/synonymdev/bitkit-ios/issues/198

This task is to unify behavior of timesheets to meet iOS behavior. In particular that means not to show backup timesheet and highbalance timesheet on balance change. Also to make sure that timesheets queue is the same on both platforms.

### PR DESCRIPTION
**Pull request by jvsena42**
Close #497 

### Description
context: https://github.com/synonymdev/bitkit-android/pull/554#issuecomment-3700028839

This branch brings the changes from #556 and #562 to a branch based on master
### Preview

[backup_and_high-balance.webm](https://github.com/user-attachments/assets/8d18db5f-4107-48cb-967f-bf96cc54d9ea)

[notifications_and_quickpay.webm](https://github.com/user-attachments/assets/1431ff50-1411-466b-ba56-5112bd778afb)

[critical_update.webm](https://github.com/user-attachments/assets/94d27393-1c86-4b08-9aa5-b06dfb3a4373)

[internal_navigation.webm](https://github.com/user-attachments/assets/45c8afd8-6167-4c69-9768-8170de98f379)

### QA Notes

Same tests from #562

### CODE REVIEW

File: app/src/main/java/to/bitkit/utils/timedsheets/sheets/AppUpdateTimedSheet.kt [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+            val currentBuildNumber = BuildConfig.VERSION_CODE
+
+            if (androidReleaseInfo.buildNumber <= currentBuildNumber) return@withContext false
+
+            if (androidReleaseInfo.isCritical) {
+                return@withContext false
+            }
+
+            return@withContext true
+        } catch (e: Exception) {
```
[the remark this answers is not in the document]
Comment (jvsena42) [reply app/src/main/java/to/bitkit/utils/timedsheets/sheets/AppUpdateTimedSheet.kt]: updated in #554

**Comment by jvsena42** [comment]
for this case, the user now have to leave the home and return to trigger the backup sheet
https://github.com/synonymdev/bitkit-android/actions/runs/20617706363/job/59213780179?pr=565

**Comment by jvsena42** [comment]
> With regards to HighBalanceSheet I'm seeing this behavior locally (sheet appearing automatically, without trigger): [#556 (comment)](https://github.com/synonymdev/bitkit-android/pull/556#issuecomment-3698648454)
> 
> @jvsena42 In light of your research [synonymdev/bitkit-ios#294 (comment)](https://github.com/synonymdev/bitkit-ios/issues/294#issuecomment-3699127212) we're going for iOS behavior, I guess?

should have the same behavior of iOS, could you check if your branch is updated?

File: app/src/main/java/to/bitkit/utils/timedsheets/TimedSheetUtils.kt [hunk 2]
```diff
@@ -0,0 +1,21 @@
+package to.bitkit.utils.timedsheets
```
Comment (ovitrif) [inline app/src/main/java/to/bitkit/utils/timedsheets/TimedSheetUtils.kt]: we don't need another package only for this.

Also, we should collectively put shared code in "shared", not utils.

and lastly, I things that belong together should stay together, this global scope function is better placed in `TimedSheetManager` class, which should also include the `TimedSheetItem` definition.

Comment (ovitrif) [inline app/src/main/java/to/bitkit/utils/timedsheets/TimedSheetUtils.kt]: nit: package of all these should be `.ui.sheets.*` where it could be grouped into `*sheets.timed` if desired.

**Review by ovitrif — APPROVED** [review]
tAck

approved with nit-only type of comments

**Comment by jvsena42** [comment]
Better wait for #554 merge to apply these suggestions to don't cause a big conflict, @ovitrif WDYT?
